package eu.nordtal.s2.common.access;

import java.time.Instant;
import java.util.UUID;

/**
 * One row of {@code access_grant}: a period of access with a start, an end and a reason.
 * <p>
 * Grants are appended, never extended in place - see
 * {@link AccessDirectory#grantAccess(String, int, AccessSource, UUID)}. A revoked grant keeps its
 * window and stops counting.
 * </p>
 *
 * @param id               surrogate key, generated by PostgreSQL
 * @param discordId        the Discord account the period belongs to
 * @param validFrom        when the period starts; {@code max(now, current valid_until)} at the
 *                         moment it was written
 * @param validUntil       when the period ends, always after {@code validFrom}
 * @param source           purchase or admin grant
 * @param paymentRequestId the request that paid for it, {@code null} for an admin grant
 * @param revoked          when an admin revoked it, {@code null} while it counts
 * @param created          when the row was written
 */
public record AccessGrant(
        UUID id,
        String discordId,
        Instant validFrom,
        Instant validUntil,
        AccessSource source,
        UUID paymentRequestId,
        Instant revoked,
        Instant created) {

    /**
     * @param at the point in time to test
     * @return whether this grant covers {@code at} and has not been revoked
     */
    public boolean coversAt(final Instant at) {
        return revoked == null && !validFrom.isAfter(at) && validUntil.isAfter(at);
    }
}
