/** The cache key of every query, in one place so a write can name exactly what it makes stale. */

export const SECOND = 1000

export const keys = {
  me: ["me"] as const,
  services: ["services"] as const,
  topology: ["topology"] as const,
  service: (name: string) => ["service", name] as const,
  plugins: (name: string) => ["plugins", name] as const,
  pluginSearch: (name: string, query: string) => ["plugin-search", name, query] as const,
  host: ["host"] as const,
  backups: ["backups"] as const,
  schedule: ["schedule"] as const,
  runs: (limit: number) => ["runs", limit] as const,
  /** Under "runs", so asking for a run and cancelling one refresh it with the list. */
  activeRun: ["runs", "active"] as const,
  run: (id: string) => ["run", id] as const,
  available: ["available"] as const,
  metrics: (subject: string, metric: string, minutes: number) => ["metrics", subject, metric, minutes] as const,
  season: ["season"] as const,
  people: ["people"] as const,
  payments: ["payments"] as const,
  openPayments: ["payments", "open"] as const,
  grants: (discordId: string) => ["grants", discordId] as const,
  journal: (action: string, subject: string) => ["journal", action, subject] as const,
  actions: (limit: number) => ["actions", limit] as const,
  settings: ["settings"] as const,
  commandRun: (id: string) => ["command-run", id] as const,
  smpTrack: ["smp-track"] as const,
  announcements: ["announcements"] as const,
  hungerGamesRound: ["hunger-games-round"] as const,
  configs: ["configs"] as const,
  agent: ["agent"] as const,
  config: (file: string) => ["config", file] as const,
  guildRoles: ["guild-roles"] as const,
  guildChannels: ["guild-channels"] as const,
  messageBundles: ["message-bundles"] as const,
  descriptors: ["descriptors"] as const,
  gameData: ["game-data"] as const,
  messageBundle: (path: string) => ["message-bundle", path] as const,
  messageExamples: ["message-examples"] as const,
  messageTones: ["message-tones"] as const,
  glyphs: ["glyphs"] as const,
  webPushPublicKey: ["web-push-public-key"] as const,
  webPushSubscription: ["web-push-subscription"] as const,
  webPushDevices: ["web-push-devices"] as const,
  alerts: ["alerts"] as const,
  alertPreferences: ["alert-preferences"] as const,
}
