package eu.nordtal.s2.common.pack;

import eu.nordtal.s2.common.Glyphs;
import eu.nordtal.s2.common.RepositoryRoot;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.UncheckedIOException;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Holds {@link Glyphs}, the four font files and the pack's PNGs to each other.
 *
 * <h2>Why a test and not a look</h2>
 * The four are mirrors of one allocation - {@code resource-pack/README.md}'s code point table says
 * so - and every way they can drift is invisible until a client renders it. A constant the font
 * does not declare draws a missing-glyph box; a font entry pointing at a texture that is not there
 * draws nothing; a cell the sheet never filled in draws a blank the same width as the glyph. None
 * of those fail a build, none of them log anything, and the one that actually happened - a boss bar
 * drawing the admin nametag, because the component named no font - sat in a screenshot for four
 * days before anybody read it as a bug rather than as missing art.
 *
 * <p>This is the check that would have caught the next one cheaply. It runs on {@code check}, needs
 * no server and no Docker, and every file it reads is declared in {@code common/build.gradle.kts}
 * so that editing the pack actually re-runs it.</p>
 *
 * <h2>What it cannot say</h2>
 * That the art is any good. Almost all of it is placeholder-quality, generated by
 * {@code resource-pack/tools/generate_dummy_textures.py}; "has pixels in the right cell" is the
 * whole claim. Which placeholders deserve real art is a decision for the owner, and it is on the
 * checklist outside this repository.
 */
class ResourcePackTest {

    private static final String ASSETS = "resource-pack/src/assets";

    private static final FontFile DEFAULT_FONT =
            FontFile.load("minecraft:default", ASSETS + "/minecraft/font/default.json");
    private static final FontFile BOARD_FONT =
            FontFile.load(Glyphs.FONT_BOARD, ASSETS + "/nordtal/font/board.json");
    private static final FontFile BOSSBAR_FONT =
            FontFile.load(Glyphs.FONT_BOSSBAR, ASSETS + "/nordtal/font/bossbar.json");
    private static final FontFile GUI_FONT =
            FontFile.load(Glyphs.FONT_GUI, ASSETS + "/nordtal/font/gui.json");

    /**
     * The six row fonts, which declare exactly the same characters at six different ascents.
     *
     * <p>They are checked one by one rather than as one font, because "the same characters" is
     * precisely what can stop being true: the six files are generated together and a hand edit to
     * one of them is invisible from every other check here. {@link #theRowFontsAreSixCopies} is
     * what asserts they still agree.</p>
     */
    private static final List<FontFile> GUI_ROW_FONTS = java.util.stream.IntStream.range(0, 6)
            .mapToObj(row -> FontFile.load(Glyphs.FONT_GUI_ROWS[row],
                    ASSETS + "/nordtal/font/gui_r" + row + ".json"))
            .toList();

    private static final List<FontFile> FONTS = Stream.concat(
            Stream.of(DEFAULT_FONT, BOARD_FONT, BOSSBAR_FONT, GUI_FONT),
            GUI_ROW_FONTS.stream()).toList();

    /**
     * The message keys whose text is drawn inside a boss bar, mirroring what
     * {@code SmpHud} and {@code HudRenderer} actually pass to {@code Messages}.
     *
     * <p>{@code smp.milestone.} is broader than the HUD needs - {@code smp.milestone.completed} is
     * a chat line - but a milestone's display name is looked up under the same prefix and there is
     * no way to tell the two apart from here. Checking one chat string too many is the safe
     * direction: everything the boss bar font can draw, chat can draw too.</p>
     */
    private static final List<String> HUD_KEY_PREFIXES =
            List.of("smp.hud.", "smp.world.", "smp.milestone.", "smp.navigate.", "hg.hud.");

    private static final List<String> HUD_BUNDLES = List.of(
            "smp/src/main/resources/messages/smp/en.properties",
            "smp/src/main/resources/messages/smp/de.properties",
            "hunger-games/src/main/resources/messages/hunger-games/en.properties",
            "hunger-games/src/main/resources/messages/hunger-games/de.properties");

    @Test
    @DisplayName("every Glyphs constant is declared by the font its name says it belongs to")
    void everyConstantIsInItsFont() {
        final List<String> missing = new ArrayList<>();
        forEachGlyph((name, value) -> {
            final FontFile font = fontFor(name);
            if (value.codePointCount(0, value.length()) != 1) {
                return;
            }
            if (!font.covers(value.codePointAt(0))) {
                missing.add("Glyphs.%s = U+%04X is not declared in %s"
                        .formatted(name, value.codePointAt(0), font.id()));
            }
        });
        assertEquals(List.of(), missing,
                "Glyphs, the font files and resource-pack/README.md's allocation table are three"
                        + " mirrors of one table - a constant missing from its font draws a"
                        + " missing-glyph box, and nothing else says so");
    }

    @Test
    @DisplayName("every bitmap provider names a texture that exists")
    void everyProviderHasItsTexture() {
        final List<String> missing = new ArrayList<>();
        for (final FontFile font : FONTS) {
            for (final FontFile.Bitmap bitmap : font.bitmaps()) {
                if (!Files.isRegularFile(bitmap.texture())) {
                    missing.add(font.id() + " -> " + bitmap.textureId());
                }
            }
        }
        assertEquals(List.of(), missing, "a font entry pointing at a texture that is not in the"
                + " pack draws nothing at all, and the client logs nothing about it");
    }

    @Test
    @DisplayName("every character a font declares has pixels in its cell")
    void everyDeclaredCharacterIsDrawn() {
        final List<String> blank = new ArrayList<>();
        for (final FontFile font : FONTS) {
            for (final FontFile.Bitmap bitmap : font.bitmaps()) {
                final BufferedImage image = read(bitmap.texture());
                final int cellWidth = image.getWidth() / bitmap.columns();
                final int cellHeight = image.getHeight() / bitmap.rows();
                for (int row = 0; row < bitmap.rows(); row++) {
                    for (int column = 0; column < bitmap.columns(); column++) {
                        final int codePoint = bitmap.grid().get(row)[column];
                        if (codePoint == 0 || codePoint == ' ') {
                            continue;
                        }
                        if (!hasPixels(image, column * cellWidth, row * cellHeight,
                                cellWidth, cellHeight)) {
                            blank.add("%s declares U+%04X at row %d column %d of %s, and that cell"
                                    .formatted(font.id(), codePoint, row, column, bitmap.textureId())
                                    + " is empty");
                        }
                    }
                }
            }
        }
        assertEquals(List.of(), blank, "a declared character with no pixels is not a missing glyph"
                + " on screen - it is a gap the width of the glyph, which reads as a layout bug");
    }

    @Test
    @DisplayName("every drawn cell is claimed by a character")
    void everyDrawnCellIsReachable() {
        final List<String> orphans = new ArrayList<>();
        for (final FontFile font : FONTS) {
            for (final FontFile.Bitmap bitmap : font.bitmaps()) {
                final BufferedImage image = read(bitmap.texture());
                final int cellWidth = image.getWidth() / bitmap.columns();
                final int cellHeight = image.getHeight() / bitmap.rows();
                for (int row = 0; row < bitmap.rows(); row++) {
                    for (int column = 0; column < bitmap.columns(); column++) {
                        if (bitmap.grid().get(row)[column] != 0) {
                            continue;
                        }
                        if (hasPixels(image, column * cellWidth, row * cellHeight,
                                cellWidth, cellHeight)) {
                            orphans.add("%s: row %d column %d of %s is drawn but no character"
                                    .formatted(font.id(), row, column, bitmap.textureId())
                                    + " points at it");
                        }
                    }
                }
            }
        }
        assertEquals(List.of(), orphans, "art nothing can reach is art nobody will ever see - it is"
                + " a chars entry somebody forgot, not a spare cell");
    }

    @Test
    @DisplayName("the six row fonts declare the same characters, one row apart")
    void theRowFontsAreSixCopies() {
        final Set<Integer> first = GUI_ROW_FONTS.get(0).declared();
        for (int row = 1; row < GUI_ROW_FONTS.size(); row++) {
            assertEquals(new TreeSet<>(first), new TreeSet<>(GUI_ROW_FONTS.get(row).declared()),
                    Glyphs.FONT_GUI_ROWS[row] + " declares a different set of characters from"
                            + " nordtal:gui_r0. The six are one font drawn at six heights - a"
                            + " character in five of them is a row that renders on five rows and"
                            + " draws a missing-glyph box on the sixth");
        }
    }

    @Test
    @DisplayName("the bossbar font can write German")
    void theBossbarFontCanWriteGerman() {
        final List<String> missing = new ArrayList<>();
        for (final int codePoint : "äöüÄÖÜß".codePoints().toArray()) {
            if (!BOSSBAR_FONT.covers(codePoint)) {
                missing.add(new String(Character.toChars(codePoint)));
            }
        }
        assertEquals(List.of(), missing,
                "nordtal:bossbar carries its own ascii sheet, so a character the vanilla font has"
                        + " is not a character this one has. It shipped without a single umlaut"
                        + " until 2026-09-04, which is why every German HUD string was written"
                        + " around them; resource-pack/tools/draw_ascii_extras.py draws them");
    }

    @Test
    @DisplayName("every character a boss bar line can contain is in the bossbar font")
    void theBossbarFontCoversTheHudStrings() {
        final Map<String, Set<Integer>> missing = new LinkedHashMap<>();
        for (final String bundle : HUD_BUNDLES) {
            properties(bundle).forEach((key, value) -> {
                if (HUD_KEY_PREFIXES.stream().noneMatch(String.valueOf(key)::startsWith)) {
                    return;
                }
                String.valueOf(value).codePoints().forEach(codePoint -> {
                    if (!BOSSBAR_FONT.covers(codePoint)) {
                        missing.computeIfAbsent(bundle + " " + key, ignored -> new TreeSet<>())
                                .add(codePoint);
                    }
                });
            });
        }
        assertEquals(Map.of(), missing,
                "a boss bar line is rendered in nordtal:bossbar, whose ascii sheet is a subset of"
                        + " the vanilla one - a character it does not carry reaches the player as a"
                        + " missing-glyph box in the middle of the HUD. What a placeholder is"
                        + " replaced with at runtime is not checkable from here.");
    }

    @Test
    @DisplayName("the vanilla boss bar sprites are fully transparent")
    void theVanillaBossBarSpritesAreBlank() {
        for (final String sprite : List.of("white_background", "white_progress")) {
            final Path path = RepositoryRoot.resolve(
                    ASSETS + "/minecraft/textures/gui/sprites/boss_bar/" + sprite + ".png");
            final BufferedImage image = read(path);
            assertTrue(!hasPixels(image, 0, 0, image.getWidth(), image.getHeight()),
                    sprite + ".png has to be fully transparent: the whole HUD technique is a"
                            + " vanilla boss bar made invisible with a composed background drawn"
                            + " in its name. A pixel here puts the vanilla bar back on screen"
                            + " behind ours.");
        }
    }

    @Test
    @DisplayName("every texture under nordtal:textures is reachable from a font")
    void noOrphanedFontTexture() {
        final Set<String> referenced = new LinkedHashSet<>();
        FONTS.forEach(font -> font.bitmaps().forEach(bitmap -> referenced.add(bitmap.textureId())));

        final Path textures = RepositoryRoot.resolve(ASSETS + "/nordtal/textures");
        final List<String> orphans = new ArrayList<>();
        try (Stream<Path> walk = Files.walk(textures)) {
            walk.filter(path -> path.toString().endsWith(".png")).forEach(path -> {
                final String relative = RepositoryRoot.relative(textures, path);
                // item/ is the balloon's model textures, which hang off nordtal/models/item and
                // not off any font. Everything else under textures/ exists for a font.
                if (relative.startsWith("item/")) {
                    return;
                }
                if (!referenced.contains("nordtal:" + relative)) {
                    orphans.add("nordtal:" + relative);
                }
            });
        } catch (final IOException e) {
            throw new UncheckedIOException("cannot walk " + textures, e);
        }
        orphans.sort(String::compareTo);
        assertEquals(List.of(), orphans, "a texture no font names is either a font entry somebody"
                + " forgot or dead weight in the pack zip; both are worth knowing about");
    }

    /**
     * The vanilla screens the pack rewords, and the one of them that draws a glyph.
     *
     * <p>{@code minecraft/lang/*.json} is the single place in this repository where the
     * <b>client's own</b> language setting decides what somebody reads - docs/i18n.md accepts that,
     * because a JSON file in a zip cannot consult {@code discord_user.locale}. It is accepted only
     * because what lives there is three cosmetic strings; this is the check that they stay three
     * cosmetic strings that actually render.</p>
     */
    private static final List<String> LANG_FILES = List.of(
            ASSETS + "/minecraft/lang/en_us.json",
            ASSETS + "/minecraft/lang/de_de.json");

    @Test
    @DisplayName("every glyph a vanilla lang override draws is one the pack declares")
    void everyLangGlyphIsDeclared() {
        // It was not. Both files put the logo on the pause menu at U+E021, which is where it lived
        // until the pack moved to Supplementary Private Use Area-A on 2026-09-04 (Glyphs#cp) - and
        // nothing moved with it, because nothing compares a lang file to a font. The title of the
        // one screen every player opens has been a missing-glyph box ever since, in both languages,
        // and it looks exactly like art that was never drawn.
        final List<String> undeclared = new ArrayList<>();
        for (final String relative : LANG_FILES) {
            final Path file = RepositoryRoot.resolve(relative);
            assertTrue(Files.isRegularFile(file), relative + " no longer exists");
            // PARSED, not read as text. A lang file writes a code point as a \\uXXXX escape - the
            // whole reason it may hold one at all is that the escape keeps it greppable - so
            // scanning the raw bytes finds the six characters of the escape and never the
            // character, and the check passes on exactly the file it was written for.
            //
            // A lang override renders in minecraft:default and nowhere else - a screen title cannot
            // name a font - so it is that one font the code point has to be in, not any of the four.
            for (final Map.Entry<String, com.google.gson.JsonElement> entry
                    : com.google.gson.JsonParser.parseString(readText(file)).getAsJsonObject()
                            .entrySet()) {
                entry.getValue().getAsString().codePoints()
                        .filter(ResourcePackTest::isPrivateUse)
                        .forEach(codePoint -> {
                            if (!DEFAULT_FONT.covers(codePoint)) {
                                undeclared.add(relative + " draws U+"
                                        + Integer.toHexString(codePoint).toUpperCase()
                                        + " for " + entry.getKey()
                                        + ", which minecraft:default does not declare");
                            }
                        });
            }
        }
        assertEquals(List.of(), undeclared,
                "a lang override naming a code point no font carries is a missing-glyph box on a"
                        + " vanilla screen - and it is invisible from every other check here,"
                        + " because a lang file is not a font and not a message bundle");
    }

    private static boolean isPrivateUse(final int codePoint) {
        return (codePoint >= 0xE000 && codePoint <= 0xF8FF)
                || (codePoint >= 0xF0000 && codePoint <= 0xFFFFD)
                || (codePoint >= 0x100000 && codePoint <= 0x10FFFD);
    }

    /** {@code readText}, not {@code read}: the other one in this class answers a PNG. */
    private static String readText(final Path file) {
        try {
            return Files.readString(file, StandardCharsets.UTF_8);
        } catch (final IOException e) {
            throw new UncheckedIOException("cannot read " + file, e);
        }
    }

    // --- helpers ---------------------------------------------------------------------------

    /** Feeds every {@code public static final String} constant of {@link Glyphs} to the consumer. */
    private static void forEachGlyph(final java.util.function.BiConsumer<String, String> consumer) {
        for (final Field field : Glyphs.class.getDeclaredFields()) {
            if (!Modifier.isStatic(field.getModifiers()) || !Modifier.isPublic(field.getModifiers())) {
                continue;
            }
            // The font keys are namespaced ids, not code points; BossBarFontTest checks those.
            if (field.getName().startsWith("FONT_")) {
                continue;
            }
            try {
                final Object value = field.get(null);
                if (value instanceof String text) {
                    consumer.accept(field.getName(), text);
                } else if (value instanceof String[] array) {
                    for (int i = 0; i < array.length; i++) {
                        consumer.accept(field.getName() + "[" + i + "]", array[i]);
                    }
                }
            } catch (final IllegalAccessException e) {
                throw new IllegalStateException("cannot read Glyphs." + field.getName(), e);
            }
        }
    }

    /** The font a constant belongs to, taken from its name - the grouping {@link Glyphs} uses. */
    private static FontFile fontFor(final String constant) {
        if (constant.startsWith("BOSSBAR_")) {
            return BOSSBAR_FONT;
        }
        if (constant.startsWith("BOARD_")) {
            return BOARD_FONT;
        }
        // GUI_ROW_* before GUI_*: a row glyph lives in the six row fonts and nordtal:gui declares
        // none of them, so the prefix test has to be the more specific one first.
        if (constant.startsWith("GUI_ROW_")) {
            return GUI_ROW_FONTS.get(0);
        }
        if (constant.startsWith("GUI_")) {
            return GUI_FONT;
        }
        return DEFAULT_FONT;
    }

    private static boolean hasPixels(final BufferedImage image, final int x, final int y,
                                     final int width, final int height) {
        for (int row = y; row < y + height; row++) {
            for (int column = x; column < x + width; column++) {
                if ((image.getRGB(column, row) >>> 24) != 0) {
                    return true;
                }
            }
        }
        return false;
    }

    private static BufferedImage read(final Path path) {
        try {
            final BufferedImage image = ImageIO.read(path.toFile());
            if (image == null) {
                throw new IllegalStateException(path + " is not an image ImageIO can read");
            }
            return image;
        } catch (final IOException e) {
            throw new UncheckedIOException("cannot read " + path, e);
        }
    }

    /** Reads a bundle the way {@code Messages} does - UTF-8, never the platform default. */
    private static Properties properties(final String relative) {
        final Properties properties = new Properties();
        try (Reader reader = new InputStreamReader(
                Files.newInputStream(RepositoryRoot.resolve(relative)), StandardCharsets.UTF_8)) {
            properties.load(reader);
        } catch (final IOException e) {
            throw new UncheckedIOException("cannot read " + relative, e);
        }
        return properties;
    }
}
