package eu.nordtal.s2.accessbot.persistence.model;

import eu.nordtal.s2.accessbot.model.ContributionTier;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Comparator;
import java.util.UUID;

/**
 * One row of the {@code contribution} table.
 * <p>
 * A plain mutable bean, not a JPA entity: the persistence layer moved to JDBI with jcore 2.0.0.
 * The no-args constructor and the setters are what JDBI's {@code BeanMapper} needs to hydrate an
 * instance, and the getters are what {@code @BindBean} reads when inserting one. The mapping from
 * {@code snake_case} columns to these camelCase properties is configured explicitly in
 * {@link eu.nordtal.s2.accessbot.persistence.dao.ContributionRepository} rather than left to a
 * JDBI default.
 * </p>
 * <p>
 * {@link #euroAmount} is a {@code float} while the column is {@code numeric(10,2)}. The column is
 * the source of truth for the value; the Java side stays {@code float} because
 * {@link ContributionTier} and the contribution-scheduling comparator in
 * {@code ContributionRepository} are built on primitive comparisons. See the module notes.
 * </p>
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Contribution {

    /** Generated by PostgreSQL ({@code gen_random_uuid()}) and read back on insert. */
    private UUID id;

    /** Discord snowflake of the member the contribution is credited to. */
    private String receiverId;

    private float euroAmount;

    private LocalDateTime created;

    /** {@code 0} means "never expires"; anything positive is a countdown in seconds. */
    private long durationSeconds;

    /** The bunq payment this row was created from, or {@code -1} for a synthetic entry. */
    private long bunqPaymentId;

    public ContributionTier contributionTier() {
        return Arrays.stream(ContributionTier.values())
                .filter(tier -> tier.getEuroAmount() <= euroAmount)
                .max(Comparator.comparingInt(ContributionTier::getEuroAmount))
                .orElse(null);
    }


}
