#!/usr/bin/env python3
"""Writes how far every `nordtal:bossbar` glyph moves the cursor, as a resource in :common.

The server sizes each pill to its content, so it needs these widths. An advance is derived as
the client does: a `space` provider's number, or a bitmap's rightmost drawn column plus two.
The first provider to declare a code point wins. `BossBarAdvancesTest` fails when the resource
is stale.

Usage:
    python3 resource-pack/tools/export_bossbar_advances.py
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pngio import read_png, rightmost_drawn_column  # noqa: E402  (path set above)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ASSETS = os.path.join(REPO_ROOT, "resource-pack", "src", "assets")
FONT = os.path.join(ASSETS, "nordtal", "font", "bossbar.json")
OUT = os.path.join(REPO_ROOT, "common", "src", "main", "resources", "nordtal", "hud",
                   "bossbar-advances.properties")


def texture_path(texture_id):
    namespace, _, path = texture_id.rpartition(":")
    return os.path.join(ASSETS, namespace or "minecraft", "textures", path)


def advances():
    with open(FONT, encoding="utf-8") as f:
        providers = json.load(f)["providers"]

    table = {}
    for provider in providers:
        if provider["type"] == "space":
            for text, advance in provider["advances"].items():
                for character in text:
                    table.setdefault(ord(character), advance)
            continue

        width, height, rgba = read_png(texture_path(provider["file"]))
        rows = provider["chars"]
        columns = len(rows[0])
        cell_width, cell_height = width // columns, height // len(rows)
        scale = provider["height"] / cell_height
        for row_index, row in enumerate(rows):
            assert len(row) == columns, provider["file"]
            for column_index, character in enumerate(row):
                code_point = ord(character)
                if code_point == 0 or code_point in table:
                    continue
                rightmost = rightmost_drawn_column(rgba, width, height, column_index * cell_width,
                                                   row_index * cell_height, cell_width, cell_height)
                # The client's formula, kept whole so a scaled provider stays correct.
                table[code_point] = int(0.5 + (rightmost + 1) * scale) + 1
    return table


def main():
    table = advances()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# GENERATED by resource-pack/tools/export_bossbar_advances.py; do not edit.\n")
        f.write("# How far each nordtal:bossbar code point moves the cursor, in HUD pixels,\n")
        f.write("# derived from bossbar.json and its PNGs the way the client derives it.\n")
        f.write("# BossBarAdvancesTest fails the build if this file and the pack disagree.\n")
        for code_point in sorted(table):
            f.write(f"{code_point:X}={table[code_point]}\n")
    print(f"wrote {os.path.relpath(OUT, REPO_ROOT)} ({len(table)} code points)")


if __name__ == "__main__":
    main()
