#!/usr/bin/env python3
"""Writes down how far every `nordtal:bossbar` glyph moves the cursor, for the plugins.

WHY THE PLUGINS NEED THIS. Since 2026-09-05 a HUD line is one pill per piece of information,
and a pill is drawn as wide as what it holds. The server composes the pill, so the server has
to know the width of "Nordtal" in the bossbar font - and it can, because that font's ascii
sheet is ours: every advance is a property of a PNG in this repository, not of the client.
The plugins do not ship the pack, so the table travels as a resource in :common instead.

HOW AN ADVANCE IS DERIVED, the way the client does it (and the way BoardFrameTest and
MenuTitleTest already derive it): a `space` provider's number, or for a bitmap the
rightmost column of the glyph's cell that carries any alpha, plus one for that column
itself and one the client adds after every glyph. The first provider to declare a code
point wins, which is why the space provider's " " (+3) beats the ascii sheet's.

WHAT KEEPS IT HONEST. `BossBarAdvancesTest` in :common derives the same table from the
same files with the same rule and fails if this resource disagrees - so a redrawn icon
whose rightmost column moved is caught at `check`, not on a player's screen as a pill
one pixel too narrow.

Usage:
    python3 resource-pack/tools/export_bossbar_advances.py
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pngio import read_png, rightmost_drawn_column  # noqa: E402  (path set above)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ASSETS = os.path.join(REPO_ROOT, "resource-pack", "src", "assets")
FONT = os.path.join(ASSETS, "nordtal", "font", "bossbar.json")
OUT = os.path.join(REPO_ROOT, "common", "src", "main", "resources", "nordtal", "hud",
                   "bossbar-advances.properties")


def texture_path(texture_id):
    namespace, _, path = texture_id.rpartition(":")
    return os.path.join(ASSETS, namespace or "minecraft", "textures", path)


def advances():
    with open(FONT, encoding="utf-8") as f:
        providers = json.load(f)["providers"]

    table = {}
    for provider in providers:
        if provider["type"] == "space":
            for text, advance in provider["advances"].items():
                for character in text:
                    table.setdefault(ord(character), advance)
            continue

        width, height, rgba = read_png(texture_path(provider["file"]))
        rows = provider["chars"]
        columns = len(rows[0])
        cell_width, cell_height = width // columns, height // len(rows)
        scale = provider["height"] / cell_height
        for row_index, row in enumerate(rows):
            assert len(row) == columns, provider["file"]
            for column_index, character in enumerate(row):
                code_point = ord(character)
                if code_point == 0 or code_point in table:
                    continue
                rightmost = rightmost_drawn_column(rgba, width, height, column_index * cell_width,
                                                   row_index * cell_height, cell_width, cell_height)
                # The client: int(0.5 + width * scale) + 1, with width = rightmost + 1. Every
                # provider here is drawn 1:1, so scale is 1.0 and this is rightmost + 2 - but
                # the formula is kept whole so a scaled provider does not silently lie.
                table[code_point] = int(0.5 + (rightmost + 1) * scale) + 1
    return table


def main():
    table = advances()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# GENERATED by resource-pack/tools/export_bossbar_advances.py - do not edit.\n")
        f.write("# How far each nordtal:bossbar code point moves the cursor, in HUD pixels,\n")
        f.write("# derived from bossbar.json and its PNGs the way the client derives it.\n")
        f.write("# BossBarAdvancesTest fails the build if this file and the pack disagree.\n")
        for code_point in sorted(table):
            f.write(f"{code_point:X}={table[code_point]}\n")
    print(f"wrote {os.path.relpath(OUT, REPO_ROOT)} ({len(table)} code points)")


if __name__ == "__main__":
    main()
