package eu.nordtal.s2.common.audit;

import java.time.Instant;
import java.util.UUID;

/**
 * One line of {@code audit_log}: what happened, who caused it, who it was about, and free text for
 * the human reading it.
 *
 * <p>The table is append-only by discipline rather than by trigger, and this package only reads it,
 * so an entry never changes after it is written.
 *
 * <p>Every component is a JDK type: this record is serialised straight to JSON.
 *
 * @param id       surrogate key, generated by PostgreSQL
 * @param occurred when it happened, by the database's clock
 * @param action   {@code LINK}, {@code UNLINK}, {@code GRANT_ACCESS}, {@code REVOKE_ACCESS},
 *                 {@code SETTLE}, ... Deliberately a {@link String} and not an enum: the column has
 *                 no CHECK constraint, so the set of values is whatever has been written over a
 *                 season, and a journal that cannot show a line it does not recognise is not a
 *                 journal
 * @param actor    the Discord id of the admin who caused it, {@code null} when the bot acted on its
 *                 own - which is most lines
 * @param subject  the Discord id the line is about, {@code null} when there is no one person
 * @param mcUuid   the Minecraft account the line is about, for link and unlink; {@code null}
 *                 otherwise
 * @param detail   free text, {@code null} when the action says everything
 */
public record AuditEntry(
        UUID id, Instant occurred, String action, String actor, String subject, UUID mcUuid, String detail) {}
