package eu.nordtal.displaytags.config;

import java.io.File;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.Plugin;

/**
 * Migrates a DisplayTags v1 configuration to the v2 layout.
 *
 * v1 kept every key below the {@code nametags} root; v2 keeps them below {@code nametag}, as
 * generated by the Spec library. This has to run <b>before</b> {@code Specs.fromFile(...)} touches
 * the file, otherwise Spec rewrites the configuration with its defaults and the user's v1 settings
 * are lost silently.
 */
public final class ConfigurationMigrator {
    private static final String FILE_NAME = "config.yml";
    private static final String BACKUP_NAME = "config.yml.v1.bak";

    private static final String LEGACY_ROOT = "nametags";
    private static final String ROOT = "nametag";

    /**
     * Maps a v1 key (relative to {@code nametags}) to its v2 key (relative to {@code nametag}).
     * There is no v1 counterpart for {@code display.offset}: v1 hardcoded a translation of
     * (0, 0.25, 0), which is exactly the v2 default, so letting the default apply keeps the
     * old behaviour.
     */
    private static final Map<String, String> KEYS = new LinkedHashMap<>();

    static {
        KEYS.put("enabled", "enabled");
        KEYS.put("show-self", "show-to-self");
        KEYS.put("update-interval", "update-interval");
        KEYS.put("visibility-distance", "visibility-distance");
        KEYS.put("display.lines", "display.lines");
        KEYS.put("display.text-shadow", "display.text-shadow");
        KEYS.put("display.see-through", "display.see-through");
        KEYS.put("display.text-alignment", "display.text-alignment");
        KEYS.put("display.background", "display.background");
        KEYS.put("display.billboard", "display.billboard");
        KEYS.put("display.scale.x", "display.scale.x");
        KEYS.put("display.scale.y", "display.scale.y");
        KEYS.put("display.scale.z", "display.scale.z");
    }

    private ConfigurationMigrator() {}

    /**
     * Migrates the plugin's {@code config.yml} if — and only if — it still uses the v1 format.
     * Never throws: a failed migration leaves the file untouched and lets the server start.
     */
    public static void migrate(final Plugin plugin) {
        final Logger logger = plugin.getLogger();
        final File file = new File(plugin.getDataFolder(), FILE_NAME);

        if (!file.isFile()) return;

        try {
            // loadConfiguration() never throws; a broken file simply yields an empty configuration.
            final YamlConfiguration config = YamlConfiguration.loadConfiguration(file);

            // A v2 file has no "nametags" root, so it is never touched again.
            if (!config.isConfigurationSection(LEGACY_ROOT)) return;

            logger.info("Found a DisplayTags v1 configuration (settings below the 'nametags' key).");
            logger.info("Migrating it to the DisplayTags v2 format (settings below the 'nametag' key)...");

            final List<String> migrated = new ArrayList<>();
            final List<String> skipped = new ArrayList<>();
            migrateKeys(config, migrated, skipped);
            final List<String> unknown = collectUnknownKeys(config);

            // Drop the old root so this migration cannot run a second time.
            config.set(LEGACY_ROOT, null);

            final File backup = backupFile(plugin.getDataFolder());
            Files.copy(file.toPath(), backup.toPath());
            config.save(file);

            logResults(logger, file, backup, migrated, skipped, unknown);
        } catch (Exception error) {
            logger.severe("Failed to migrate the DisplayTags v1 configuration: " + error);
            logger.severe("Continuing with the configuration as-is. Your settings may have fallen back to defaults.");
        }
    }

    private static void migrateKeys(
            final YamlConfiguration config, final List<String> migrated, final List<String> skipped) {
        for (final Map.Entry<String, String> entry : KEYS.entrySet()) {
            final String from = LEGACY_ROOT + "." + entry.getKey();
            final String to = ROOT + "." + entry.getValue();

            final Object value = config.get(from);
            if (value == null) continue; // missing key -> the v2 default applies

            if (config.isSet(to)) {
                // Both roots present: never overwrite a value that is already in the v2 format.
                skipped.add(to);
                continue;
            }

            config.set(to, convert(entry.getValue(), value));
            migrated.add(from + " -> " + to);
        }
    }

    private static List<String> collectUnknownKeys(final YamlConfiguration config) {
        final List<String> unknown = new ArrayList<>();
        for (final String key : config.getConfigurationSection(LEGACY_ROOT).getKeys(true)) {
            if (config.isConfigurationSection(LEGACY_ROOT + "." + key)) continue;
            if (!KEYS.containsKey(key)) unknown.add(LEGACY_ROOT + "." + key);
        }
        return unknown;
    }

    private static void logResults(
            final Logger logger,
            final File file,
            final File backup,
            final List<String> migrated,
            final List<String> skipped,
            final List<String> unknown) {
        for (final String line : migrated) logger.info("  Migrated " + line);
        for (final String line : skipped)
            logger.warning("  Kept your existing value of " + line + " (it was already set).");
        for (final String line : unknown)
            logger.warning("  Dropped unknown setting " + line + " (no equivalent in v2).");

        logger.info("Migrated " + migrated.size() + " setting(s). Your old configuration was backed up to:");
        logger.info("  " + backup.getAbsolutePath());
        logger.info("Please review " + file.getAbsolutePath() + " — comments and new options were regenerated.");
    }

    /**
     * v1 wrote the scale as whole numbers ({@code x: 1}), which SnakeYAML reads as an Integer.
     * The v2 vector type expects doubles, so numeric scale values are widened here.
     */
    private static Object convert(final String key, final Object value) {
        if (key.startsWith("display.scale.") && value instanceof Number number) {
            return number.doubleValue();
        }

        // v1 wrote see-through as a YAML boolean; the migrated file gets the equivalent string form.
        if (key.equals("display.see-through") && value instanceof Boolean flag) {
            return flag.toString();
        }

        return value;
    }

    /**
     * Returns a backup file that does not exist yet, so an earlier backup is never overwritten.
     */
    private static File backupFile(final File folder) {
        File backup = new File(folder, BACKUP_NAME);

        for (int index = 1; backup.exists(); index++) {
            backup = new File(folder, BACKUP_NAME + "." + index);
        }

        return backup;
    }
}
