package eu.nordtal.s2.discordbot.access.payment;

import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

/**
 * One row of {@code payment_request}: what somebody is trying to buy, the reference printed on the
 * bunq.me tab, and where in its life it is.
 * <p>
 * <b>This row is the purchase flow's state.</b> Season 1 kept the half-finished flow in a Guava
 * cache, so a restart silently dropped every purchase somebody was in the middle of and the button
 * they clicked next answered "setup expired". A row survives a restart, and the summary the user
 * sees is rendered from it rather than from memory.
 * </p>
 * <p>
 * A request is written as soon as the number of days is known and before a bunq tab exists, so
 * {@link #bunqTabId()} and {@link #shareUrl()} are null for a flow that has not been confirmed
 * yet. That is the whole difference between "chose 60 days" and "asked for a payment link".
 * </p>
 *
 * @param id             surrogate key, generated by PostgreSQL
 * @param reference      {@code NT-XXXXXX}, unique; the fallback matcher scrapes exactly this out
 *                       of a payment description
 * @param discordId      who is buying
 * @param days           how many days were ordered - what actually gets granted is derived from
 *                       the amount that arrives, not from this
 * @param amountCents    what the tab asks for, in cents: tier price plus the donation if chosen
 * @param donationCents  the donation part of {@code amountCents}, zero when none was chosen
 * @param status         where in its life it is
 * @param bunqTabId      the bunq.me tab, null until the user confirmed
 * @param shareUrl       the bunq.me share URL, null until the user confirmed
 * @param bunqPaymentId  the payment that settled it, null until it is paid
 * @param created        when the row was written
 * @param expires        when it stops being payable
 * @param settled        when it was booked, null unless {@code status} is {@code PAID}
 */
public record PaymentRequest(
        UUID id,
        String reference,
        String discordId,
        int days,
        int amountCents,
        int donationCents,
        PaymentRequestStatus status,
        Long bunqTabId,
        String shareUrl,
        Long bunqPaymentId,
        Instant created,
        Instant expires,
        Instant settled) {

    /** @return the bunq.me tab, if one was created */
    public Optional<Long> tab() {
        return Optional.ofNullable(bunqTabId);
    }

    /** @return whether the user asked for the donation surcharge */
    public boolean donationRequested() {
        return donationCents > 0;
    }
}
