package eu.nordtal.s2.limbo.config;

import eu.nordtal.jcore.config.spec.annotation.Comment;
import eu.nordtal.jcore.config.spec.annotation.ConfigSpec;
import eu.nordtal.jcore.config.spec.annotation.Key;
import eu.nordtal.jcore.config.spec.annotation.Order;

/**
 * {@code plugins/limbo/config.yml} - the whole of the waiting room's settings, which is small on
 * purpose.
 * <p>
 * docs/architecture.md settles what this module shows: "nothing. Black, no visible world, no other
 * players and no chat. A title in the player's language says what they are waiting for, and that is
 * the entire interface." There is correspondingly little to configure - the world it builds, how
 * often the title is refreshed, and one switch for making the screen visible while somebody is
 * working on it.
 * </p>
 * <p>
 * <b>What is deliberately not here: the waiting reason.</b> The proxy decides that and sends it on
 * {@code nordtal:limbo} ({@code eu.nordtal.s2.common.limbo.WaitReason}). Two of the three reasons
 * are facts only the proxy has, and a waiting room whose title had two sources would show the wrong
 * one on the seam.
 * </p>
 */
@ConfigSpec(header = {
        "-------------------------------------------------------------------",
        "  limbo - the season 2 waiting room",
        "-------------------------------------------------------------------",
        "Every login lands here first, whatever the phase, and stays until",
        "the proxy says otherwise: the resource pack has to be applied, the",
        "phase's backend has to be up, and maintenance has to be over.",
        "",
        "This server shows nothing at all. No world, no other players, no",
        "chat - one title in the player's own language, which is the entire",
        "interface. What that title SAYS is not configured here: the proxy",
        "sends the reason, and the words live in the message bundles at",
        "messages/limbo/<language>.properties.",
        "",
        "Every setting can be overridden with an environment variable named",
        "NORDTAL_LIMBO_<SETTING>, with '-' becoming '_':",
        "",
        "  world-name  ->  NORDTAL_LIMBO_WORLD_NAME",
        "",
        "The environment wins over this file and is never written back to it."
})
public interface LimboSpec {

    @Order(1)
    @Key("world-name")
    @Comment({
            "The name of the empty world this plugin creates and puts everybody in.",
            "",
            "It is created at enable if it does not exist and is generated by a chunk generator",
            "that produces nothing at all - no terrain, no bedrock, no caves, no structures and",
            "no mobs. It is NOT the server's own level-name world: players are moved out of that",
            "before they are ever spawned in it, so whatever level.dat the server ships with is",
            "never seen. Deleting this folder is safe; it is rebuilt empty on the next start."
    })
    default String worldName() {
        return "limbo";
    }

    @Order(2)
    @Key("spawn-y")
    @Comment({
            "The height everybody stands at. Nothing is at any height, so this is only about",
            "keeping players well clear of the void: a player who somehow stops flying falls,",
            "and this is how far above nothing they fall from before the plugin puts them back."
    })
    default int spawnY() {
        return 64;
    }

    @Order(3)
    @Key("title-refresh-seconds")
    @Comment({
            "How often the waiting title is re-sent to every player here.",
            "",
            "A Minecraft title expires. Without a refresh the screen goes completely black after",
            "a few seconds, which on a server whose only content is that title looks exactly like",
            "a crash. The refresh is sent with no fade so it replaces the current title rather",
            "than re-animating it; a CHANGE of reason does fade, because that is a real event the",
            "player should notice.",
            "",
            "Keep it comfortably below the title's own stay time, which this plugin sets to twice",
            "this value."
    })
    default int titleRefreshSeconds() {
        return 4;
    }

    @Order(4)
    @Key("blindness")
    @Comment({
            "Whether players here are blinded, which is what makes the screen actually black.",
            "",
            "An empty world is not a black screen - it is a sky, and a sky is a horizon, a sun",
            "and a day/night cycle. Blindness is what turns it into the nothing the design asks",
            "for. Turn it off while working ON this plugin, so you can see where you are; never",
            "in production."
    })
    default boolean blindness() {
        return true;
    }
}
